### ISSUE TITLE
Issues with Java 16

### ISSUE THREAD

**Issue by vituluss** [dyorgio/cpu-watcher#3]
When initialising the CpuWatcher class with Java 16 the following error occurs.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at dyorgio.runtime.cpu.watcher.CpuWatcher.<init>(CpuWatcher.java:47)
        at dyorgio.runtime.cpu.watcher.CpuWatcher.<init>(CpuWatcher.java:41)

Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at dyorgio.runtime.cpu.watcher.SigarUtil.<clinit>(SigarUtil.java:85)
        ... 8 more

Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at dyorgio.runtime.cpu.watcher.SigarUtil.<clinit>(SigarUtil.java:73)
        ... 8 more

Caused by: java.lang.NoSuchFieldException: no such field: java.lang.ClassLoader.sys_paths/[Ljava.lang.String;/getStatic
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:980)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3642)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findStaticVarHandle(MethodHandles.java:3242)
        ... 13 more

Caused by: java.lang.NoSuchFieldError: sys_paths
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1087)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1116)
        ... 15 more
```

In the SigarUtil class it is the 4th line here
```
Method method = MethodHandles.class.getMethod("privateLookupIn", Class.class, MethodHandles.Lookup.class);
MethodHandles.Lookup privateLookup = (MethodHandles.Lookup) method.invoke(null, ClassLoader.class, MethodHandles.lookup());
method = MethodHandles.Lookup.class.getMethod("findStaticVarHandle", Class.class, String.class, Class.class);
Object sys_paths = method.invoke(privateLookup, ClassLoader.class, "sys_paths", String[].class); // <------
method = sys_paths.getClass().getDeclaredMethod("set", sys_paths.getClass(), Object.class);
method.setAccessible(true);
method.invoke(null, sys_paths, null);
```

This is my exact Java version details

```
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by dyorgio** [comment]
Hi @vituluss, try last version (1.2.4).
